name: Build and Push to AWS ECR

on:
  release:
    types: [prereleased]

env:
  PROJECT_VERSION: ${{ github.ref_name }}
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  AWS_REGION: us-east-1
  DOCKER_REGISTRY: 977202846556.dkr.ecr.us-east-2.amazonaws.com
  DOCKER_REGISTRY_USERNAME: AWS

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      PROJECT_NAME: ${{ steps.variables.outputs.PROJECT_NAME }}
      IMAGE_NAME: ${{ steps.variables.outputs.IMAGE_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GH_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - id: variables
        name: Setting Project Name and Image Name Env Variables
        run: |
          PROJECT_NAME=$(echo $GITHUB_REPOSITORY | awk -F '/' '{print $2}')
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV        
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_OUTPUT
          IMAGE_NAME=${{ DOCKER_REGISTRY }}/$PROJECT_NAME:$PROJECT_VERSION
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
      - name: Build Native Image
        run: ./gradlew clean bootBuildImage --imageName=$IMAGE_NAME  --publishImage -PregistryUsername=${{ DOCKER_REGISTRY_USERNAME }} -PregistryToken=$(aws ecr get-login-password --region ${{ AWS_REGION }})
