name: Build and Push to AWS ECR

on:
  release:
    types: [prereleased]

env:
  PROJECT_VERSION: ${{ github.ref_name }}
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  AWS_REGION: us-east-1
  DOCKER_REGISTRY: 977202846556.dkr.ecr.us-east-2.amazonaws.com
  DOCKER_REGISTRY_USERNAME: AWS
  PROJECT_NAME: $(echo $GITHUB_REPOSITORY | awk -F '/' '{print $2}')
  IMAGE_NAME: "${{env.DOCKER_REGISTRY}}/${{env.PROJECT_NAME}}:${{env.PROJECT_VERSION}}"


jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $DOCKER_REGISTRY
          echo $PROJECT_NAME
          echo IMAGE_NAME
#      - uses: actions/checkout@v4
#      - uses: graalvm/setup-graalvm@v1
#        with:
#          java-version: '21'
#          distribution: 'graalvm'
#          github-token: ${{ secrets.GH_TOKEN }}
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ env.AWS_REGION }}
#      - name: Set Project Name env variable
#        run: echo "PROJECT_NAME=$(echo $GITHUB_REPOSITORY | awk -F '/' '{print $2}')" >> $GITHUB_ENV
#      - name: Set Image Name env variable
#        run: echo "IMAGE_NAME=${{ env.DOCKER_REGISTRY }}/$PROJECT_NAME:$PROJECT_VERSION" >> $GITHUB_ENV
#      - name: Build Native Image
#        run: ./gradlew clean bootBuildImage --imageName=$IMAGE_NAME  --publishImage -PregistryUsername=${{ DOCKER_REGISTRY_USERNAME }} -PregistryToken=$(aws ecr get-login-password --region ${{ AWS_REGION }})
